name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version:  '1.8'
        
    - name: Run a one-line script
      run: java -jar lib/junit-platform-console-standalone-1.6.0-M1.jar --select-directory=test/AVLTreeTest.java
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
